[phases.setup]
nixPkgs = ['python310']

[phases.build]
cmds = [
  'python -m venv /opt/venv',
  '/opt/venv/bin/pip install --upgrade pip',
  '/opt/venv/bin/pip install -r requirements.txt'
]

[start]
cmd = "/opt/venv/bin/python main.py"